# Generated by Django 3.0.5 on 2020-05-25 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_auto_20200523_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='plants.Category'),
        ),
    ]
