# Generated by Django 3.0.5 on 2020-05-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0003_plant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Image URL'),
        ),
        migrations.AlterField(
            model_name='userplant',
            name='image_url',
            field=models.URLField(blank=True, default='', verbose_name='Image URL'),
        ),
    ]
